In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')
import statsmodels.api as sm
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt
import seaborn as sns 

C:\Users\Usuario_1\AppData\Local\Temp\ipykernel_10972\60504849.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()

In [3]:
data = pd.read_csv('Customer-Churn.txt')

In [4]:
data.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   
2            Yes          Yes               No          No          No   
3            Yes           No              Yes         Yes          No   
4             No           No               No          No          No   

  StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0              No  Month-to-month           29.85        29.85    No  
1              No        One year           56.95       1889.5    No  
2              No  Month-to-month           53.85       108.15   Yes  
3              No        One year           42.30      1840.75    No  
4              No  Month-to-month           70.70       151.65   Yes

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   OnlineSecurity    7043 non-null   object 
 7   OnlineBackup      7043 non-null   object 
 8   DeviceProtection  7043 non-null   object 
 9   TechSupport       7043 non-null   object 
 10  StreamingTV       7043 non-null   object 
 11  StreamingMovies   7043 non-null   object 
 12  Contract          7043 non-null   object 
 13  MonthlyCharges    7043 non-null   float64
 14  TotalCharges      7043 non-null   object 
 15  Churn             7043 non-null   object 
dtypes: float64(1), int64(2), object(13)
memory

In [8]:
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   OnlineSecurity    7043 non-null   object 
 7   OnlineBackup      7043 non-null   object 
 8   DeviceProtection  7043 non-null   object 
 9   TechSupport       7043 non-null   object 
 10  StreamingTV       7043 non-null   object 
 11  StreamingMovies   7043 non-null   object 
 12  Contract          7043 non-null   object 
 13  MonthlyCharges    7043 non-null   float64
 14  TotalCharges      7032 non-null   float64
 15  Churn             7043 non-null   object 
dtypes: float64(2), int64(2), object(12)
memory

In [10]:
data['TotalCharges'].fillna(data['TotalCharges'].mode()[0], inplace=True)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   OnlineSecurity    7043 non-null   object 
 7   OnlineBackup      7043 non-null   object 
 8   DeviceProtection  7043 non-null   object 
 9   TechSupport       7043 non-null   object 
 10  StreamingTV       7043 non-null   object 
 11  StreamingMovies   7043 non-null   object 
 12  Contract          7043 non-null   object 
 13  MonthlyCharges    7043 non-null   float64
 14  TotalCharges      7043 non-null   float64
 15  Churn             7043 non-null   object 
dtypes: float64(2), int64(2), object(12)
memory

In [12]:
data=pd.get_dummies(data, columns=['gender'], drop_first=True)

In [13]:
data=pd.get_dummies(data, columns=['Partner'], drop_first=True)

In [14]:
data=pd.get_dummies(data, columns=['Dependents'], drop_first=True)

In [15]:
data=pd.get_dummies(data, columns=['PhoneService'], drop_first=True)

In [16]:
data=pd.get_dummies(data, columns=['OnlineSecurity'], drop_first=True)

In [17]:
data['OnlineBackup'] = data['OnlineBackup'].replace('No internet service', 'No')

In [18]:
data=pd.get_dummies(data, columns=['OnlineBackup'], drop_first=True)

In [19]:
data['DeviceProtection'] = data['DeviceProtection'].replace('No internet service', 'No')

In [20]:
data=pd.get_dummies(data, columns=['DeviceProtection'], drop_first=True)

In [21]:
data['TechSupport'] = data['TechSupport'].replace('No internet service', 'No')

In [22]:
data=pd.get_dummies(data, columns=['TechSupport'], drop_first=True)

In [23]:
data['StreamingTV'] = data['StreamingTV'].replace('No internet service', 'No')

In [24]:
data=pd.get_dummies(data, columns=['StreamingTV'], drop_first=True)

In [25]:
data['StreamingMovies'] = data['StreamingMovies'].replace('No internet service', 'No')

In [26]:
data=pd.get_dummies(data, columns=['StreamingMovies'], drop_first=True)

In [27]:
data['Contract'] = data['Contract'].replace({
    'Month-to-month': 0,
    'One year': 1,
    'Two year': 2
})

In [28]:
data=pd.get_dummies(data, columns=['Churn'], drop_first=True)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   SeniorCitizen                       7043 non-null   int64  
 1   tenure                              7043 non-null   int64  
 2   Contract                            7043 non-null   int64  
 3   MonthlyCharges                      7043 non-null   float64
 4   TotalCharges                        7043 non-null   float64
 5   gender_Male                         7043 non-null   bool   
 6   Partner_Yes                         7043 non-null   bool   
 7   Dependents_Yes                      7043 non-null   bool   
 8   PhoneService_Yes                    7043 non-null   bool   
 9   OnlineSecurity_No internet service  7043 non-null   bool   
 10  OnlineSecurity_Yes                  7043 non-null   bool   
 11  OnlineBackup_Yes                    7043 no

In [31]:
data.Churn_Yes.value_counts()

Churn_Yes
False    5174
True     1869
Name: count, dtype: int64

In [ ]:
#Apply SMOTE for upsampling the data

In [32]:
y = data['Churn_Yes']
X = data.drop(['Churn_Yes'], axis=1)
X_sm, y_sm = smote.fit_resample(X, y)
y_sm.value_counts()

Churn_Yes
False    5174
True     5174
Name: count, dtype: int64

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.2, random_state=42)

In [ ]:
#Use logistic regression to fit the model and compute the accuracy of the model.

In [35]:
logreg = LogisticRegression()

In [36]:
logreg.fit(X_train, y_train)

LogisticRegression()

In [37]:
y_pred = logreg.predict(X_test)

In [38]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.7951690821256039
Confusion Matrix:
[[727 294]
 [130 919]]
Classification Report:
              precision    recall  f1-score   support

       False       0.85      0.71      0.77      1021
        True       0.76      0.88      0.81      1049

    accuracy                           0.80      2070
   macro avg       0.80      0.79      0.79      2070
weighted avg       0.80      0.80      0.79      2070



In [ ]:
#Use decision tree classifier to fit the model and compute the accuracy of the model.

In [46]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.2, random_state=42)

In [49]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [50]:
classifier = DecisionTreeClassifier(random_state=42)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [51]:
y_pred = classifier.predict(X_test)

In [52]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')  # Usa 'weighted' para manejar clases desequilibradas
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Accuracy: 0.7874396135265701
Precision: 0.7875489389425501
Recall: 0.7874396135265701
F1 Score: 0.7873699180810455


In [ ]:
#Compare the accuracies of the two models.

In [53]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.33)
model = DecisionTreeClassifier()

In [55]:
cross_val_score(model, X_train, y_train, cv=10)

array([0.77521614, 0.76224784, 0.78386167, 0.77200577, 0.78499278,
       0.78932179, 0.77633478, 0.78932179, 0.77489177, 0.76479076])

In [56]:
logreg = LogisticRegression()

dectree = DecisionTreeClassifier()

import numpy as np

In [57]:
model_pipeline = [logreg, dectree]
model_names = ['Log Regression', 'Decision Tree Classifier']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Log Regression': 0.7833526703843706, 'Decision Tree Classifier': 0.7783084030922648}


In [58]:
#Apply TomekLinks for downsampling

In [59]:
from imblearn.under_sampling import TomekLinks

In [60]:
tl = TomekLinks()

In [61]:
X_tl, y_tl = tl.fit_resample(X, y)
y_tl.value_counts()

Churn_Yes
False    4604
True     1869
Name: count, dtype: int64

In [62]:
#Use logistic regression to fit the model and compute the accuracy of the model.

In [63]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X_tl, y_tl, test_size=0.2, random_state=42)

In [65]:
logreg = LogisticRegression()

In [66]:
logreg.fit(X_train, y_train)

LogisticRegression()

In [67]:
y_pred = logreg.predict(X_test)

In [68]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.8123552123552124
Confusion Matrix:
[[827  98]
 [145 225]]
Classification Report:
              precision    recall  f1-score   support

       False       0.85      0.89      0.87       925
        True       0.70      0.61      0.65       370

    accuracy                           0.81      1295
   macro avg       0.77      0.75      0.76      1295
weighted avg       0.81      0.81      0.81      1295



In [ ]:
#Use decision tree classifier to fit the model and compute the accuracy of the model.

In [69]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X_tl, y_tl, test_size=0.2, random_state=42)

In [71]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [72]:
classifier = DecisionTreeClassifier(random_state=42)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [73]:
y_pred = classifier.predict(X_test)

In [74]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')  # Usa 'weighted' para manejar clases desequilibradas
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Accuracy: 0.7235521235521235
Precision: 0.7244533584828661
Recall: 0.7235521235521235
F1 Score: 0.7239957528462753


In [ ]:
#Compare the accuracies of the two models.

In [75]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X_tl, y_tl, test_size=0.33)
model = DecisionTreeClassifier()

In [77]:
cross_val_score(model, X_train, y_train, cv=10)

array([0.75576037, 0.73963134, 0.73732719, 0.72580645, 0.70967742,
       0.73732719, 0.72979215, 0.72979215, 0.70207852, 0.75288684])

In [78]:
logreg = LogisticRegression()

dectree = DecisionTreeClassifier()

import numpy as np

In [79]:
model_pipeline = [logreg, dectree]
model_names = ['Log Regression', 'Decision Tree Classifier']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Log Regression': 0.8101930588222773, 'Decision Tree Classifier': 0.7386942454848289}


In [80]:
#You can also apply this algorithm one more time and check the how the imbalance in the two classes changed from the last time.

In [81]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X_tl, y_tl, test_size=0.33)
model = DecisionTreeClassifier()

In [83]:
cross_val_score(model, X_train, y_train, cv=10)

array([0.71889401, 0.73963134, 0.78110599, 0.75115207, 0.78801843,
       0.74423963, 0.70207852, 0.74595843, 0.75057737, 0.78290993])

In [84]:
logreg = LogisticRegression()

dectree = DecisionTreeClassifier()

import numpy as np

In [85]:
model_pipeline = [logreg, dectree]
model_names = ['Log Regression', 'Decision Tree Classifier']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Log Regression': 0.8078883792211663, 'Decision Tree Classifier': 0.7453901086621045}


In [ ]:
#Vemos como ambos metodos han cambiado. El decision tree classifier un poco más debido a que es menos robusto.